import { motion, useAnimation } from "framer-motion";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar/Navbar";
import LeftCircle from "@/components/animation/LeftCircle";
import RightCircle from "@/components/animation/RightCircle";
import YellowCircle from "@/components/animation/YellowCircle";
import TextImage from "@/components/animation/TextImage";
import Text from "@/components/animation/text";
import { useRouter } from "next/router";
import React, { useState, useEffect, useRef } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const [animationStarted, setAnimationStarted] = useState(false);

  const audioRef = React.useRef(null);
  const handleClick = () => {
    if (!animationStarted) {
      animate();
    }
  };
  const animate = async () => {
    setAnimationStarted(true);
    // await controls.start({ opacity: 1, scale: 1 });
    audioRef.current.volume = 0.1;
    audioRef.current.play();
  };

  
  useEffect(() => {
    const redirectionTimeout = setTimeout(() => {
      router.push('/home', undefined, { shallow: true });
    }, 5000);
    return () => clearTimeout(redirectionTimeout);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="menu1bolt12">
      <div
        className={styles.animationContainer}
        style={{
          height: "100vh",
          display: "flex",
          justifyContent: "center",

        }}
      >
        <div className="circle-container" onClick={handleClick}>
          <div className="circle">
            <LeftCircle />
            <RightCircle />
          </div>
          <YellowCircle />
          <TextImage />
        </div>
        <audio ref={audioRef} src="./audios/INSTRUMENTOS.mp3" />
        <div style={{position:'absolute',
          justifyContent: "center",
          left:'44%',
          bottom:'10%'}}>        
          <Text />
        </div>
      </div>
      </div>

    </>
  );
}
