import { motion, useAnimation } from 'framer-motion';
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar/Navbar";
import LeftCircle from "@/components/animation/LeftCircle";
import RightCircle from "@/components/animation/RightCircle";
import YellowCircle from "@/components/animation/YellowCircle";
import TextImage from "@/components/animation/TextImage";
import { useRouter } from 'next/router';
import React, { useEffect } from 'react';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const controls = useAnimation();
  const router = useRouter();

  const animate = async () => {
    await controls.start({ opacity: 1, scale: 1 });
  };
  useEffect(() => {
    const redirectionTimeout = setTimeout(() => {
      router.push('/home', undefined, { shallow: true });
    }, 5000);
    return () => clearTimeout(redirectionTimeout);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.animationContainer}>
        <motion.div
          initial={{ opacity: 1, scale: 1 }}
          animate={controls}
          onAnimationComplete={animate}
        >
          <div className="circle-container">
            <div className="circle">
              <LeftCircle />
              <RightCircle />
            </div>
            <YellowCircle />
            <TextImage />
          </div>
        </motion.div>
      </main>
    </>
  );
}
